### ISSUE TITLE
veSCALE leaderboard out of date

### ISSUE THREAD

**Issue by 0xGroot** [oxSaturn/veNFT-leaderboard#7]
Hey,

Looks like the veSCALE NFT leaderboard has gone out of date somehow, the data is all old even though it says it's updated.
Not sure what's causing it but we'd appreciate if you could look into it. Cheers!

**Comment by oxSaturn** [comment]
Hi, thanks for heads-up, seems the rpc I used for base was lagging 
![CleanShot-FMnVnt56@2x](https://github.com/oxSaturn/veNFT-leaderboard/assets/126733611/0d2b908f-9802-4318-919e-deebfddd2db9)

I've updated to use another one https://oxsaturn.github.io/veNFT-leaderboard/veSCALE.html
